server:
    port: 8088
spring:
  application:
    name: quickStart

# 自定义配置，心情语录
my:
  mood:
    today: 周五
    content: 期待周一
    author: "码农"
  feature:
    helloSwitch: true
    closeMsg: "该接口正在维护，10分钟之后再来吧！"